version: '3.8'

services:

  main_server:
    build:
      context: ./main_service
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb
    restart: always
    volumes:
      - ./logs:/home/logs
    ports:
      - 14565:14565

  mariadb:
    image: mariadb:latest
    volumes:
      - ./mariadb:/var/lib/mysql
    expose:
      - 3306
    env_file:
      - ./mariadb/env.txt

  pma:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 3307:80
    environment:
      - PMA_HOST=mariadb
