version: '3.8'

services:

  main_server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb
    restart: always
    ports:
      - 14565:14565
    env_file:
      - ./config.txt

  mariadb:
    image: mariadb:latest
    volumes:
      - ./mariadb:/var/lib/mysql
    expose:
      - 3306
    env_file:
      - ./config.txt
